# Generated by Django 5.1.6 on 2025-03-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SenaTareas', '0004_user_delete_tarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.PositiveIntegerField(help_text='Número de ficha (debe ser mayor o igual a 1000)', unique=True)),
                ('nombre', models.CharField(help_text='Nombre del curso', max_length=200)),
                ('tipo', models.CharField(choices=[('presencial', 'Presencial'), ('digital', 'Digital')], help_text='Tipo de curso (Presencial o Digital)', max_length=10)),
                ('sede', models.CharField(blank=True, help_text='Sede del curso (solo si es presencial)', max_length=100, null=True)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del curso')),
                ('fecha_finalizacion', models.DateField(help_text='Fecha de finalización del curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
